export const GET_STREAMER_INFO = 'GET_STREAMER_INFO';
export const GET_STREAMER_VIDEOS = 'GET_STREAMER_VIDEOS';
export const GET_LIVE_STATUS = 'GET_LIVE_STATUS';
export const GET_TOP_GAMES_INFO = 'GET_TOP_GAMES_INFO';
export const UPDATE_TOP_GAMES_INFO = 'UPDATE_TOP_GAMES_INFO';
export const UPDATE_FAV_STREAMERS = 'UPDATE_FAV_STREAMERS';