export const GET_STREAMER_INFO = 'GET_STREAMER_INFO';
export const GET_STREAMER_VIDEOS = 'GET_STREAMER_VIDEOS';
export const GET_LIVE_STATUS = 'GET_LIVE_STATUS';

export const GET_TOP_GAMES_INFO = 'GET_TOP_GAMES_INFO';
export const UPDATE_TOP_GAMES_INFO = 'UPDATE_TOP_GAMES_INFO';

export const UPDATE_FAV_STREAMERS = 'UPDATE_FAV_STREAMERS';
export const REMOVE_FAV_STREAMER = 'REMOVE_FAV_STREAMER';

export const ADD_VIDEO_PLAYLIST = 'ADD_VIDEO_PLAYLIST';
export const ADD_TITLE_PLAYLIST = 'ADD_TITLE_PLAYLIST';
export const REMOVE_VIDEO_PLAYLIST = 'REMOVE_VIDEO_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';

export const UPDATE_MODAL_STATE = 'UPDATE_MODAL_STATE';
export const UPDATE_ACTIVE_VIDEO = 'UPDATE_ACTIVE_VIDEO';
export const CLOSE_VIDEO = 'CLOSE_VIDEO';